const products = [
  {
    brand: "اپل",
    name: "آیفون 16 پرو مکس",
    description:
      "گوشی اپل آیفون 16 پرو مکس ظرفیت 256GB رم 8GB - نات اکتیو ZA/A - رجیستر شده",
    storage: "256GB",
    ram: "8GB",
    isActive: false,
    isRegistered: true,
    country: "ZA/A",
    price: 185931000,
    image: "images/imggrid1.webp",
  },
  {
    brand: "اپل",
    name: "آیفون 16",
    description:
      "گوشی اپل آیفون 16 ظرفیت 128GB رم 8GB - نات اکتیو CH/A - رجیستر شده",
    storage: "128GB",
    ram: "8GB",
    isActive: false,
    isRegistered: true,
    country: "CH/A",
    price: 107463000,
    image: "images/imggrid2.webp",
  },
  {
    brand: "سامسونگ",
    name: "گلکسی A36",
    description: "گوشی سامسونگ گلکسی A36 ظرفیت 256GB رم 8GB - ویتنام",
    storage: "256GB",
    ram: "8GB",
    isActive: true,
    isRegistered: false,
    country: "ویتنام",
    price: 33302000,
    image: "images/imggrid3.webp",
  },
  {
    brand: "شیائومی",
    name: "ردمی 14C 4G",
    description: "گوشی شیائومی ردمی 14C 4G ظرفیت 256GB رم 8GB",
    storage: "256GB",
    ram: "8GB",
    isActive: true,
    isRegistered: false,
    country: null,
    price: 13189000,
    image: "images/imggrid4.webp",
  },
  {
    brand: "سامسونگ",
    name: "گلکسی A56",
    description: "گوشی سامسونگ گلکسی A56 ظرفیت 128GB رم 8GB - ویتنام",
    storage: "128GB",
    ram: "8GB",
    isActive: true,
    isRegistered: false,
    country: "ویتنام",
    price: 35240000,
    image: "images/imggrid6.webp",
  },
  {
    brand: "اپل",
    name: "آیفون 17 پرو مکس",
    description:
      "گوشی اپل آیفون 17 پرو مکس ظرفیت 256GB رم 12GB - نات اکتیو ZA/A - رجیستر شده",
    storage: "256GB",
    ram: "12GB",
    isActive: false,
    isRegistered: true,
    country: "ZA/A",
    price: 238175000,
    image: "images/imggrid7.webp",
  },
  {
    brand: "اپل",
    name: "آیفون 17 پرو",
    description:
      "گوشی اپل آیفون 17 پرو - اکتیو ZA/A - رجیستر شده ظرفیت 256GB رم 12GB",
    storage: "256GB",
    ram: "12GB",
    isActive: true,
    isRegistered: true,
    country: "ZA/A",
    price: 212067000,
    image: "images/imggrid8.webp",
  },
  {
    brand: "سامسونگ",
    name: "گلکسی A17 4G",
    description: "گوشی سامسونگ گلکسی A17 4G ظرفیت 128GB رم 6GB - ویتنام",
    storage: "128GB",
    ram: "6GB",
    isActive: true,
    isRegistered: false,
    country: "ویتنام",
    price: 17787000,
    image: "images/imggrid9.webp",
  },
  {
    brand: "سامسونگ",
    name: "گلکسی A17 4G",
    description: "گوشی سامسونگ گلکسی A17 4G ظرفیت 128GB رم 4GB - ویتنام",
    storage: "128GB",
    ram: "4GB",
    isActive: true,
    isRegistered: false,
    country: "ویتنام",
    price: 15526000,
    image: "images/imggrid10.webp",
  },
  {
    brand: "سامسونگ",
    name: "گلکسی A17 4G",
    description: "گوشی سامسونگ گلکسی A17 4G ظرفیت 256GB رم 8GB - ویتنام",
    storage: "256GB",
    ram: "8GB",
    isActive: true,
    isRegistered: false,
    country: "ویتنام",
    price: 21908000,
    image: "images/imggrid11.webp",
  },
  {
    brand: "آنر",
    name: "پلی 10",
    description: "گوشی آنر پلی 10 ظرفیت 64GB رم 3GB",
    storage: "64GB",
    ram: "3GB",
    isActive: true,
    isRegistered: false,
    country: null,
    price: 7037000,
    image: "images/imggrid12.webp",
  },
  {
    brand: "سامسونگ",
    name: "گلکسی S25 FE",
    description: "گوشی سامسونگ گلکسی S25 FE ظرفیت 256GB رم 8GB - ویتنام",
    storage: "256GB",
    ram: "8GB",
    isActive: true,
    isRegistered: false,
    country: "ویتنام",
    price: 64973000,
    image: "images/imggrid13.webp",
  },
  {
    brand: "شیائومی",
    name: "پوکو C85 4G",
    description: "گوشی شیائومی پوکو C85 4G ظرفیت 128GB رم 6GB",
    storage: "128GB",
    ram: "6GB",
    isActive: true,
    isRegistered: false,
    country: null,
    price: 11669000,
    image: "images/imggrid14.webp",
  },
  {
    brand: "شیائومی",
    name: "پوکو C85 4G",
    description: "گوشی شیائومی پوکو C85 4G ظرفیت 256GB رم 8GB",
    storage: "256GB",
    ram: "8GB",
    isActive: true,
    isRegistered: false,
    country: null,
    price: 12944000,
    image: "images/imggrid15.webp",
  },
  {
    brand: "سامسونگ",
    name: "گلکسی A07 4G",
    description: "گوشی سامسونگ گلکسی A07 4G ظرفیت 128GB رم 6GB",
    storage: "128GB",
    ram: "6GB",
    isActive: true,
    isRegistered: false,
    country: null,
    price: 12749000,
    image: "images/imggrid16.webp",
  },
  {
    brand: "آنر",
    name: "X7d 4G",
    description: "گوشی آنر X7d 4G ظرفیت 256GB رم 8GB",
    storage: "256GB",
    ram: "8GB",
    isActive: true,
    isRegistered: false,
    country: null,
    price: 17615000,
    image: "images/imggrid17.webp",
  },
];


products.forEach((product) => {
  document.getElementById("custom-grid").innerHTML += `<div class="product">
          <img src="${product.image}" alt="" />
          <h4>${product.brand}</h4>
          <p>${product.name}</p>
          <p>${product.description}</p>
          <span class="price">${product.price} تومان</span>
        </div>`;
});
